/**
 * Seti UI Icon Mapper
 * Comprehensive extension & filename to SVG icon mapping.
 */

export const iconExtensionMap: Record<string, string> = {
  // JavaScript, TypeScript & Frameworks
  js: "javascript.svg",
  mjs: "javascript.svg",
  cjs: "javascript.svg",
  jsx: "react.svg",
  ts: "typescript.svg",
  dts: "typescript.svg",
  tsx: "react.svg",
  vue: "vue.svg",
  svelte: "svelte.svg",
  angular: "angular.svg",
  cjsx: "cjsx.svg",
  coffee: "coffee.svg",
  coffee_erb: "coffee_erb.svg",
  js_erb: "js_erb.svg",
  livescript: "livescript.svg",

  // HTML, Markups & Template Engines
  html: "html.svg",
  htm: "html.svg",
  xhtml: "html.svg",
  html_erb: "html_erb.svg",
  pug: "pug.svg",
  jade: "jade.svg",
  ejs: "ejs.svg",
  haml: "haml.svg",
  mustache: "mustache.svg",
  nunjucks: "nunjucks.svg",
  njk: "nunjucks.svg",
  jinja: "jinja.svg",
  jinja2: "jinja.svg",
  liquid: "liquid.svg",
  slim: "slim.svg",
  smarty: "smarty.svg",
  twig: "twig.svg",
  hbs: "mustache.svg",
  handlebars: "mustache.svg",

  // Styling & CSS Pre-processors
  css: "css.svg",
  scss: "sass.svg",
  sass: "sass.svg",
  less: "less.svg",
  styl: "stylus.svg",
  stylus: "stylus.svg",

  // Programming & Scripting Languages
  py: "python.svg",
  pyc: "python.svg",
  pyd: "python.svg",
  pyw: "python.svg",
  php: "php.svg",
  java: "java.svg",
  jar: "java.svg",
  class: "java.svg",
  cpp: "cpp.svg",
  cc: "cpp.svg",
  cxx: "cpp.svg",
  c: "c.svg",
  h: "c.svg",
  hpp: "cpp.svg",
  hxx: "cpp.svg",
  cs: "c-sharp.svg",
  csx: "c-sharp.svg",
  fs: "f-sharp.svg",
  fsi: "f-sharp.svg",
  fsscript: "f-sharp.svg",
  go: "go.svg",
  rs: "rust.svg",
  kt: "kotlin.svg",
  kts: "kotlin.svg",
  dart: "dart.svg",
  rb: "ruby.svg",
  rbw: "ruby.svg",
  r: "R.svg",
  rmd: "R.svg",
  swift: "swift.svg",
  lua: "lua.svg",
  jl: "julia.svg",
  ex: "elixir.svg",
  exs: "elixir.svg",
  exscript: "elixir_script.svg",
  elm: "elm.svg",
  erl: "hex.svg",
  hrl: "hex.svg",
  clj: "clojure.svg",
  cljs: "clojure.svg",
  cljc: "clojure.svg",
  edn: "clojure.svg",
  hs: "haskell.svg",
  lhs: "haskell.svg",
  hx: "haxe.svg",
  nim: "nim.svg",
  ml: "ocaml.svg",
  mli: "ocaml.svg",
  pas: "mdo.svg",
  pp: "puppet.svg",
  pl: "perl.svg",
  pm: "perl.svg",
  ps1: "powershell.svg",
  psm1: "powershell.svg",
  psd1: "powershell.svg",
  prolog: "prolog.svg",
  pro: "prolog.svg",
  purs: "purescript.svg",
  re: "reasonml.svg",
  rei: "reasonml.svg",
  res: "rescript.svg",
  resi: "rescript.svg",
  scala: "scala.svg",
  sc: "scala.svg",
  sh: "shell.svg",
  bash: "shell.svg",
  zsh: "shell.svg",
  fish: "shell.svg",
  sol: "ethereum.svg",
  v: "vala.svg",
  vala: "vala.svg",
  zig: "zig.svg",
  asm: "asm.svg",
  s: "asm.svg",
  d: "d.svg",
  cu: "cu.svg",
  cuh: "cu.svg",
  bsl: "bsl.svg",
  os: "bsl.svg",

  // Configs, Data & Serialization
  json: "json.svg",
  jsonc: "json.svg",
  json5: "json.svg",
  xml: "xml.svg",
  xsl: "xml.svg",
  xslt: "xml.svg",
  yml: "yml.svg",
  yaml: "yml.svg",
  csv: "csv.svg",
  tsv: "csv.svg",
  env: "config.svg",
  config: "config.svg",
  conf: "config.svg",
  ini: "config.svg",
  toml: "config.svg",
  lock: "lock.svg",
  properties: "config.svg",

  // Markdown & Documentation
  md: "markdown.svg",
  markdown: "markdown.svg",
  mdown: "markdown.svg",
  mkd: "markdown.svg",
  argdown: "argdown.svg",
  tex: "tex.svg",
  sty: "tex.svg",
  dtx: "tex.svg",
  pdf: "pdf.svg",
  doc: "word.svg",
  docx: "word.svg",
  xls: "xls.svg",
  xlsx: "xls.svg",
  ppt: "powerpoint.svg",
  pptx: "powerpoint.svg",
  rst: "info.svg",

  // Tools, Build Systems & Infrastructure
  dockerfile: "docker.svg",
  dockerignore: "docker.svg",
  vite: "vite.svg",
  webpack: "webpack.svg",
  rollup: "rollup.svg",
  gradle: "gradle.svg",
  maven: "maven.svg",
  sbt: "sbt.svg",
  tf: "terraform.svg",
  tfvars: "terraform.svg",
  prisma: "prisma.svg",
  bicep: "bicep.svg",
  bazel: "bazel.svg",
  bower: "bower.svg",
  cake: "cake.svg",
  godot: "godot.svg",
  gd: "godot.svg",
  platformio: "platformio.svg",
  puppet: "puppet.svg",

  // Databases & ORM
  db: "db.svg",
  sql: "db.svg",
  sqlite: "db.svg",
  sqlite3: "db.svg",
  mdb: "db.svg",
  pgsql: "db.svg",
  postgres: "db.svg",

  // WebAssembly & Low Level
  wasm: "wasm.svg",
  wat: "wat.svg",

  // Media, Images & Fonts
  svg: "svg.svg",
  png: "image.svg",
  jpg: "image.svg",
  jpeg: "image.svg",
  gif: "image.svg",
  webp: "image.svg",
  bmp: "image.svg",
  ico: "favicon.svg",
  icns: "favicon.svg",
  ttf: "font.svg",
  woff: "font.svg",
  woff2: "font.svg",
  eot: "font.svg",
  otf: "font.svg",
  mp3: "audio.svg",
  wav: "audio.svg",
  ogg: "audio.svg",
  flac: "audio.svg",
  mp4: "video.svg",
  mkv: "video.svg",
  avi: "video.svg",
  mov: "video.svg",
  webm: "video.svg",

  // Design Software
  psd: "photoshop.svg",
  ai: "illustrator.svg",

  // Archives & Compressed
  zip: "zip.svg",
  tar: "zip.svg",
  gz: "zip.svg",
  bz2: "zip.svg",
  xz: "zip.svg",
  "7z": "zip.svg",
  rar: "zip.svg",

  // AI & Data Science
  ipynb: "notebook.svg",

  // Logic & Verification
  pddl: "pddl.svg",
  plan: "plan.svg",

  graphql: "graphql.svg",
  gql: "graphql.svg",

  gsp: "grails.svg",

  hh: "hacklang.svg",
  hack: "hacklang.svg",

  xpi: "firefox.svg",

  plist: "apple.svg",
  storyboard: "apple.svg",
  xib: "apple.svg",
  xcconfig: "apple.svg",
  ipa: "apple.svg",

  exe: "windows.svg",
  dll: "windows.svg",
  msi: "windows.svg",

  cls: "salesforce.svg",
  trigger: "salesforce.svg",
  cmp: "salesforce.svg",
  page: "salesforce.svg",
};